### ISSUE TITLE
Working with two virtualAlexaBuilder

### ISSUE THREAD

**Issue by dixya** [bespoken/virtual-alexa#56] opened 2018-05-23 01:25 UTC
I have test that rely on two alexas connecting simultaneously. 
```typescript
beforeEach(async () => {
    // the below file paths are relative to where package.json is for some reason
    // maybe because it's where the test command is called...
    server = new bst.LambdaServer('./init', 9997, true);
    alexa = new va.VirtualAlexaBuilder()
        .handler('./init.handler')
        .interactionModelFile('./speechAssets/InteractionModel.json')
        .applicationID(getAppId())
        .create();
    alexa2 = new va.VirtualAlexaBuilder()
        .handler('./init.handler')
        .interactionModelFile('./speechAssets/InteractionModel.json')
        .applicationID(getAppId())
        .create();

    alexa.context().device().setID('test-device-id-1');
    alexa2.context().device().setID('test-device-id-2');
    await server.start();
}, 5000);
``` 
While testing one suite of tests, I am using only alexa for launching (not alexa2). But, sometimes it gets 'test-device-id-2' instead of 'test-device-id-1'. The occurrence of this is seemingly random. In the `beforeEach` of my test I am resetting the value of deviceId.
```typescript
    alexa.context().device().setID('test-device-id-1');
    alexa2.context().device().setID('test-device-id-2');
```
In the middle of some test (using alexa, not alexa2):
```typescript
// ...
const logoutResp = await alexa.intend('LogoutIntent');
expect(logoutResp.response.outputSpeech.ssml).toBeDefined();
expect(logoutResp.response.outputSpeech.ssml).toMatchSnapshot();
// ...
```
The request comes through to my LambdaServer
```typescript
// ...
export const handler = (event: Alexa.RequestBody<Alexa.Request>, context: Alexa.Context, callback: (err: any, response: any) => void): void => {
    let deviceId = event.context.System.device.deviceId;
    console.log(`[index][handler]: deviceId = ${deviceId}`);
// ...
```
with deviceId for alexa2 (not alexa)
```
[index][handler]: deviceId = test-device-id-2
```

Is handling 2 alexa clients simultaneously supported? It's important for some of my tests as users interact with one another in my skill. It has worked in the past for us, but now we're having issues. I tried updating to the lastest versions of `bst` and `virtual-alexa`
```json
"dependencies": {
    "alexa-sdk": "1.0.25",
    "axios": "0.18.0",
    "colors": "1.2.4",
    "dotenv": "5.0.1"
  },
  "devDependencies": {
    "@types/colors": "1.2.1",
    "@types/jest": "^22.2.3",
    "@types/node": "10.0.8",
    "bespoken-tools": "1.2.10",
    "jest": "22.4.3",
    "jshint": "2.9.5",
    "nodemon": "1.17.4",
    "serverless": "1.27.0",
    "serverless-webpack": "5.1.3",
    "ts-jest": "22.4.5",
    "ts-loader": "4.2.0",
    "ts-node": "6.0.2",
    "tslint": "5.10.0",
    "typescript": "2.8.3",
    "virtual-alexa": "0.6.1",
    "webpack": "4.6.0",
    "webpack-cli": "2.1.2",
    "webpack-node-externals": "1.7.2"
},
```

**Comment by jkelvie** [comment] 2018-05-23 04:06
Hi @dixya this is definitely an interesting issue. Virtual-alexa was not built explicitly to handle concurrency, but it should work fine for it - there is no global state across virtual alexa instances. So I am not sure how this could happen.

To try to replicate it, I created this simple repository:
https://github.com/jkelvie/virtual-alexa-concurrency-test

Running it, I was not able to see any issues with concurrency - the results for the device ID all seem to come from the correct virtual-alexa instance.

Perhaps though there is some aspect of the scenario you are working with that I am missing. I did try to boil it down to a minimal amount of code (based on the get-facts example skill) to eliminate any other variables.

Also, I did notice you are instantiating a Lambda server - this is not necessary when you use the "handler" method - that automatically invokes the correct Lambda code for you - the server is not actually used. Instead, the Lambda module is directly called programmatically.

**Comment by dixya** [comment] 2018-05-23 17:41
Thank you for your response. Your suggestion to not instantiating a lambda server is very helpful.

**Comment by jkelvie** [comment] 2018-05-23 18:35
Glad to hear it @dixya - and can you share what the skill is? I'm just curious - one in which users interact directly sounds very cool.

**Comment by dixya** [comment] 2018-05-23 19:54
It is just a chatting skill. You could probably see it soon as the public alexa skill .

**Comment by CoreyCole** [comment] 2018-05-23 22:25
@jkelvie maybe we can add you to the beta once it's ready! 😄

**Comment by jkelvie** [comment] 2018-05-23 23:45
Hi @CoreyCole - I would be delighted to participated!

**Comment by jkelvie** [comment] 2018-05-23 23:45
And I should add - I'm going to close this issue now - please let us know if you observe any other odd behavior with concurrency.

**Closed by jkelvie** 2018-05-23 23:45 UTC

**Comment by CoreyCole** [comment] 2018-05-24 23:10
By the way, we were still running into non-deterministic behavior even after removing the bst.LambdaServer from our tests. Sometimes the device ID would still randomly switch to that of `alexa2` even when we were using `alexa`. For anyone else trying to use multiple virtual-alexas, we were able to work around this by extreme overkill in our `beforeEach` and `afterEach` functions:

```typescript
beforeEach(async () => {
    alexa.context().device().setID(testConstants.deviceId);
    alexa2.context().device().setID(testConstants.deviceId2);
    await alexa.utter('logout');
    await alexa2.utter('logout');
    alexa.context().device().setID(testConstants.deviceId);
    alexa2.context().device().setID(testConstants.deviceId2);
}, 5000);

afterEach(async () => {
    alexa.context().device().setID(testConstants.deviceId);
    alexa2.context().device().setID(testConstants.deviceId2);
    await alexa.utter('logout');
    await alexa2.utter('logout');
    alexa.context().device().setID(testConstants.deviceId);
    alexa2.context().device().setID(testConstants.deviceId2);
});
```

@jkelvie I'm not sure if you want to open this back up if you think there is a fixable issue here. Up to you. Thanks again for all the support!

**Comment by jkelvie** [comment] 2018-05-25 00:08
Please take a look at the project I created to try to replicate. It is important to know what is different about how you are running virtual alexa versus this project:
https://github.com/jkelvie/virtual-alexa-concurrency-test

With that test case I created, the issue is not replicable.

**Comment by CoreyCole** [comment] 2018-05-25 00:39
Interesting, thank you for the test repo. We are not using `alexa.filter()` I cloned your repository and commented out these parts
```javascript
// alexa.filter((request) => {
// 	request.instance = "test-device-id-1";
// });

// alexa2.filter((request) => {
// 	request.instance = "test-device-id-2";
// });
```
and I reproduced the error 
```
      26 | 	if (request.instance !== request.context.System.device.deviceId) {
   > 27 | 		throw Error("This should not happen - device IDs do not match");
      28 | 	}
```

**Comment by jkelvie** [comment] 2018-05-25 00:48
Without that value set, the test has to fail - it's not even a test at that
point. All that's doing is ensuring that there is a difference in behavior
between the two alexas.

-John

**Comment by CoreyCole** [comment] 2018-05-25 01:28
Sorry, I misunderstood what your code was doing. I've changed it up a bit and tried everything I could to try to reproduce, but was unable. I even changed to typescript/ts-jest. All of these tests run asynchronously with jest, so even that mixing up stuff didn't reproduce. I'll get back to you if I learn more about what is causing it to happen in our actual skill's code.

```typescript
import * as va from 'virtual-alexa';

describe('concurrency test', () => {
	let alexa: va.VirtualAlexa;
	let alexa2: va.VirtualAlexa;
	beforeAll(() => {
		alexa = new va.VirtualAlexaBuilder()
	        .handler('index.handler')
	        .interactionModelFile('../../models/en-US.json')
        	.create();
    	
		alexa2 = new va.VirtualAlexaBuilder()
	        .handler('index.handler')
	        .interactionModelFile('../../models/en-US.json')
	        .create();

	    alexa.context().device().setID('test-device-id-1');
		alexa2.context().device().setID('test-device-id-2');
	});
	
	test('send many calls', async () => {
		await keepCalling(alexa, 'test-device-id-1');
		await keepCalling(alexa2, 'test-device-id-2');
	}, 10000);
	test('send more calls', async () => {
		await keepCalling(alexa2, 'test-device-id-2');
		await keepCalling(alexa, 'test-device-id-1');
	}, 10000);
	test('send more calls2', async () => {
		await keepCalling(alexa2, 'test-device-id-2');
		await keepCalling(alexa, 'test-device-id-1');
		await keepCalling(alexa2, 'test-device-id-2');
	}, 10000);
	test('send more calls3', async () => {
		await keepCalling(alexa, 'test-device-id-1');
		await keepCalling(alexa2, 'test-device-id-2');
		await keepCalling(alexa, 'test-device-id-1');
	}, 10000);
	test('send more calls4', async () => {
		await keepCalling(alexa, 'test-device-id-1');
		await keepCalling(alexa2, 'test-device-id-2');
		await keepCalling(alexa2, 'test-device-id-2');
		await keepCalling(alexa, 'test-device-id-1');
	}, 10000);
	test('send more calls5', async () => {
		await keepCalling(alexa2, 'test-device-id-2');
		await keepCalling(alexa, 'test-device-id-1');
		await keepCalling(alexa, 'test-device-id-1');
		await keepCalling(alexa2, 'test-device-id-2');
	}, 10000);
});

async function keepCalling(virtualAlexa, deviceId) {
	for (let i = 0; i < 10; i++) {
		const res = await virtualAlexa.launch();
		expect(res.response.outputSpeech.ssml).toEqual(`<speak>${deviceId}</speak>`);
	}
}
```
